name: "Update readme with rss Actions"
description: "Fetch latest blog posts and add it to GitHub profile's readme dynamically. Support multiple rss format."
author: "armingli"
inputs:
  rss_list:
    description: "RSS feed url"
    default: ""
    required: true
  readme_path:
    description: "Path of readme file"
    default: "./README.md"
    required: false
  max_post:
    description: "Max number of posts"
    default: "5"
    required: false


runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'file-text'
  color: 'red'